import React from "react";

const generateIdOrName = (label) => {
  return label
    ? label.toLowerCase().replace(/\s+/g, "-")
    : `select-${Math.random().toString(36).substr(2, 9)}`;
};

const Select = ({
  options = [], // Array of { value, label }
  id,
  name,
  value,
  onChange,
  disabled = false,
  required = false,
  placeholder = "Select an option",
  topSpace = 0,
  bottomSpace = 0,
  className = "",
  icon, // Optional icon
}) => {
  const autoGeneratedId = id || generateIdOrName(placeholder);
  const autoGeneratedName = name || generateIdOrName(placeholder);

  const validTopSpace = Math.min(Math.max(topSpace, 0), 5);
  const validBottomSpace = Math.min(Math.max(bottomSpace, 0), 5);

  return (
    <div
      className={`relative ${topSpace > 0 ? `mt-${validTopSpace}` : ""} ${
        bottomSpace > 0 ? `mb-${validBottomSpace}` : ""
      } ${className}`}
    >
      {/* Icon */}
      {icon && (
        <span className="absolute inset-y-0 left-3 flex items-center text-gray-300">
          {icon}
        </span>
      )}

      {/* Select Box */}
      <select
        id={autoGeneratedId}
        name={autoGeneratedName}
        value={value}
        onChange={onChange}
        disabled={disabled}
        required={required}
        className={`block w-full rounded-3xl border border-gray-300 bg-white py-2 text-gray-900 shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 disabled:bg-gray-100 disabled:cursor-not-allowed ${
          icon ? "pl-8 " : "px-3"
        }`} // 👈 Added left padding when icon exists
      >
        <option value="" disabled>
          {placeholder}
        </option>
        {options.map((opt) => (
          <option key={opt.value} value={opt.value}>
            {opt.label}
          </option>
        ))}
      </select>
    </div>
  );
};

export default Select;
