import React from "react";

const generateIdOrName = (label) => {
  return label
    ? label.toLowerCase().replace(/\s+/g, "-")
    : `input-${Math.random().toString(36).substr(2, 9)}`;
};

const InputSelect = ({
  label,
  value,
  onChange,
  id,
  name,
  options = [], // Array of options for the select
  optionValue = "value", // Key for the option value
  optionLabel = "label", // Key for the option label
  placeholder = "Select an option", // Placeholder as the default first option
  disabled = false,
}) => {
  const autoGeneratedId = id || generateIdOrName(placeholder);
  const autoGeneratedName = name || generateIdOrName(placeholder);

  const getNestedValue = (obj, path) => {
    return path.split(".").reduce((value, key) => value?.[key], obj);
  };

  return (
    <>
      <div className="flex flex-col items-start justify-center gap-1 mb-auto">
        {label && (
          <label
            className="form-label mb-0"
            htmlFor={autoGeneratedId}
            style={{ whiteSpace: "nowrap" }}
          >
            {label}
          </label>
        )}
        <select
          className="text-[14px] px-3 py-[5px] rounded-full border border-gray-200 shadow-sm bg-gray-100 min-w-[100px]"
          aria-label={placeholder}
          value={value}
          onChange={onChange}
          id={autoGeneratedId}
          name={autoGeneratedName}
          disabled={disabled}
          style={{
            flex: "1", // Makes select take remaining space
            minWidth: "0", // Prevents overflow
            fontSize: "14px",
          }}
        >
          {options?.map((option, i) => (
            <option
              key={i}
              value={getNestedValue(option, optionValue)}
              className="font-plusJakartaSans"
            >
              {getNestedValue(option, optionLabel)}
            </option>
          ))}
        </select>
      </div>
    </>
  );
};

export default InputSelect;
