import { Eye, EyeOff } from "lucide-react";
import React, { useState } from "react";

const generateIdOrName = (label) => {
  return label
    ? label.toLowerCase().replace(/\s+/g, "-")
    : `input-${Math.random().toString(36).substr(2, 9)}`;
};

const Input = ({
  value,
  type = "text",
  id,
  name,
  onChange,
  disabled = false,
  autoComplete = "off",
  maxLength,
  minLength,
  required = false,
  placeholder = "",
  topSpace = 0,
  bottomSpace = 0,
  className = "",
  icon,
}) => {
  const [isSecureEntry, setIsSecureEntry] = useState(true);

  const autoGeneratedId = id || generateIdOrName(placeholder);
  const autoGeneratedName = name || generateIdOrName(placeholder);

  // Tailwind spacing classes: mt-0..mt-5, mb-0..mb-5
  const validTopSpace = Math.min(Math.max(topSpace, 0), 5);
  const validBottomSpace = Math.min(Math.max(bottomSpace, 0), 5);

  return (
    <div
      className={`relative flex items-center border border-gray-300 rounded-3xl px-3 py-2 mt-${validTopSpace} mb-${validBottomSpace} ${className} ${
        disabled ? "bg-gray-100 cursor-not-allowed" : "bg-white"
      }`}
    >
      {icon && <span className="mr-2 text-gray-400">{icon}</span>}

      <input
        type={
          type === "password" ? (isSecureEntry ? "password" : "text") : type
        }
        id={autoGeneratedId}
        name={autoGeneratedName}
        value={value}
        onChange={onChange}
        disabled={disabled}
        autoComplete={autoComplete}
        maxLength={maxLength}
        minLength={minLength}
        required={required}
        placeholder={placeholder}
        className="flex-1 outline-none bg-transparent text-gray-900 placeholder-gray-400"
      />

      {type === "password" && (
        <button
          type="button"
          onClick={() => setIsSecureEntry((prev) => !prev)}
          className="ml-2 text-gray-400 hover:text-gray-600 focus:outline-none"
        >
          {isSecureEntry ? (
            <Eye className="text-[#3DB47D]" size={20} />
          ) : (
            <EyeOff className="text-[#3DB47D]" size={20} />
          )}
        </button>
      )}
    </div>
  );
};

export default Input;
